### ISSUE TITLE
Webhooks - PAYMENT.SALE.COMPLETED - Not being sent in sandbox 

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#103]
*Migrated issue from https://github.com/paypal/PayPal-Java-SDK/issues/303*

>Known workarounds or alternative products: Instant Payment Notification
>For internal bookkeeping: PPPLMER-36755

 [PAYMENT.SALE.COMPLETED](https://developer.paypal.com/docs/integration/direct/webhooks/event-names/?mark=PAYMENT.SALE.COMPLETED#sales) webhooks are not being sent in sandbox.

**Comment by mayank9294** [comment]
Sandbox webhook notification for payment completion is not working from last month.
Please update.

**Comment by mayank9294** [comment]
Can you please update, is it issue from paypal end?Are you facing same issue in paypal live? then i have to implement something else to maintain recurring payment.

**Comment by pp-randy** [comment]
This issue is not impacting production.  I apologize for the inconvenience with your webhook testing.  

I recommend Instant Payment Notification for a backup mechanism.

**Comment by greggy** [comment]
But will this event be fixed for sandbox?

2017-07-06 17:03 GMT+03:00 Randy <notifications@github.com>:

**Comment by pp-randy** [comment]
Yes, we are working on a resolution for this webhook issue.

**Comment by tadzik** [comment]
I'm not getting any notifications from sandbox on IPN either; are both of those broken?

**Comment by pp-randy** [comment]
I'm getting IPN currently from the sandbox.  Does the IPN simulator work for you @tadzik?

**Comment by mayank9294** [comment]
@pp-randy Can you please share expected fix date for sandbox webhook issue?I have code written to validate webhook event but unable to test it and simulator's events can not be validated.

**Comment by tadzik** [comment]
@pp-randy ah, no, it does not: "URL with port number is not allowed for IPN". Why exactly is that the requirement? It's common at my clients' to have development machines run at the same hostname but different ports. I can of course proxy it through some other host, but it seems like a rather bizarre requirement imo.

Also, it'd be nice if the place where you configure the IPN URL ([here](https://www.sandbox.paypal.com/cgi-bin/customerprofileweb?cmd=%5fprofile%2dipn%2dnotify)) was aware of it and warned ahead of time.

**Comment by tadzik** [comment]
Even changing a URL to one that works with the simulator, the IPN was not delivered, and it doesn't show up in the IPN history in the sandbox. The payment in question is PAY-4LK94368WF811873HLFSQBAQ.

**Comment by tipo94** [comment]
Do you have an ETA for this issue? It's been more than a month that we are waiting to push our code to production but we cannot test it. It makes the hierarchy worried that the solution won't be stable...

**Comment by pp-randy** [comment]
Unfortunately, I am not able to provide an ETA.  We have identified a possible fix and are working on the resolution.

**Comment by pp-randy** [comment]
We pushed a change to help with sandbox webhooks this morning.  The issue is resolved in my testing.  

Please run some tests and let me know if you are now receiving the webhooks.

**Comment by tipo94** [comment]
It is working for me, thanks

**Comment by adamlehmann** [comment]
I'm still having an issue with this. If I create a sandbox webhook to subscribe to all events and send to requestb.in it will work when I use the Sandbox Webhooks Simulator, but if I process a sale through paypal in sandbox mode requestb.in never receives anything.

**Comment by pp-randy** [comment]
What is the funding source? Webhooks are not sent for direct credit card payments.

**Comment by adamlehmann** [comment]
Funding source is PayPal Balance.

The call shows as a success in the API Call History: /v1/payments/payment | 79b5702ddee3e

But nothing shows up in the notifications and no webhook is fired.

**Comment by greggy** [comment]
I also have a question. Does this event has a delay? I use it with
Billing&Agreement and sometimes it's fired after several hours. Is it
normal?

2017-08-04 6:22 GMT+03:00 adamlehmann <notifications@github.com>:

**Comment by optiroot** [comment]
Same problem as @adamlehmann, no Webhooks get fired. In fact, I subscribed to all events and after a completed payment in PayPal and redirect to my website, no Webhooks is fired and any shows up in the Webhooks events. Still in sandbox. 

I can instead receive mock simulation webhooks. It seems a problem that affects just sandbox Environment.

I've disabled too "Review Payment" in the sandbox accounts 'cause I read in a PP GitHub bug tracker from a member that could've give problems with webhooks, but nothing. Even because I subscribed for all events.

**Comment by xiaoleih41** [comment]
I have reported this issue.

**Comment by xiaoleih41** [comment]
It appears to be solved. I have received the webhooks. Please try again.

**Comment by glyphsharie** [comment]
Is it just me or anyone else still experience this issue again?

1) I have set a webhook with valid https.
2) I subscribe to events using the sandbox platform
3) Postman and Webhook simulator works
4) Whenever a payment is completed , **it's not hitting my webhook URL.**


Can someone help me?

**Comment by optiroot** [comment]
@glyphsharie I noticed that (at least for me) to let a webhook fire you need to execute the payment too. It is not enough that the user clicks "pay" and gets redirected to your website. You also need to execute the payment using the data you receive from the redirect. In this case the webhook gets fired. This was my problem (it isn't said in the docs).

**Comment by glyphsharie** [comment]
@optiroot thank you for your reply. I also found the same solution yesterday via StackOverflow. I kinda stalled time on this because documentation doesn't provide us. So yes, I've execute the payment upon receiving the GET request on my return_url. That's when my Webhook gets fired finally.

Thanks pal!

**Comment by optiroot** [comment]
@glyphsharie exactly what happened to me... I stalled for days on this, because there isn't any reference about this thing. @xiaoleih41 Could this be added (doing a request) to the PayPal docs API? Because it isn't really obvious and I think that so much people - like us - that had problems with WebHooks maybe is because of this.

**Comment by xiaoleih41** [comment]
@optiroot. Certainly, can you please point out the exact confusing documentation and URL, I will make detail request accordingly.

**Comment by kenjohnson** [comment]
The mock simulator will write to requestb.in okay, but it will not 
 write to my file ValidateWebhookEvent.php. 

 Case #1
  Set mock simulator url to  requestb.in
  event type: choose Payment sale completed. 
  result: can successfully see the data in requestb.in

 Case #2
  Set mock simulator url to https://me.mydomain.com/~ken/ValidateWebhookEvent.php
  event type: choose Payment sale completed.
  result: 
    the mock simulator says it was sent okay, but it 
   does not appear to touch the ValidateWebhookEvent.php file
  additional info:	  
  1) I have reduced the contents of my  ValidateWebhookEvent.php file to this.
```
    echo 'in ValidateWebhookEvent  ' . date("h:i:s");
    ini_set('error_log','./php.errorwebhook.log');
    error_log("\nSTARTING in ValidateWebhookEvent.php\n");
```
  2) If I type this URL into my browser it shows up and does echo the text above. 
  3) If I run the file from the command line (php ValidateWebhookEvent.php) it 
     will execute and write to the error file. 
  
  Should this be able to work?
  Is it okay to put tilde (~ken) in the mock simulator url?
  Is there a string length limit to the mock simulator URL string? 
  Any idea why this isn't working?

  My configuration:
     PayPal-PHP-SDK 1.12.0
     working in sandbox

**Comment by xiaoleih41** [comment]
@kenjohnson Have your issue solved?  As the original issue was solved, please open a new issue. I will limit the conversation on this old issue.
